name = "wrangler2-repro-534"
main = "dist/index.mjs"

# set in environment:
# - CF_ACCOUNT_ID
# - CF_ZONE_ID

workers_dev = false

# `wrangler1 dev` wont work on a subdomain
# `wrangler2 dev` wont do image resizing
route = "my-image-resizing-enabled-domain.com/*"

compatibility_date = "2021-11-15"
compatibility_flags = []

[build]
command = "npm run build"

[miniflare]
