name = "wrangler2-repro-534"
type = "javascript"

# set in environment:
# - CF_ACCOUNT_ID
# - CF_ZONE_ID

workers_dev = false

# `wrangler1 dev` wont work on a subdomain
# `wrangler2 dev` wont do image resizing
route = "image-resizing-enabled-zone.com/wrangler2-repro-534*"

compatibility_date = "2021-11-15"
compatibility_flags = []

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
